[package]
name = "nsh_parser"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
futures = "0"
tokio = { version = "1", features = ["full"] }
async-stream = "0"
tokio-stream = "0"
async-recursion = "1"
