[package]
name = "nsh"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "nsh"
path = "main.rs"

[dependencies]
anyhow = "1"

nsh_parser = { path = "../parser" }

[dev-dependencies]
pretty_assertions = "1"
