[package]
name = "nsh"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "nsh"
path = "main.rs"

[dependencies]
log = "0"
anyhow = "1"
nix = "0"

nsh_parser = { path = "../parser" }

[dev-dependencies]
pretty_assertions = "1"
